apiVersion: v1
kind: ServiceAccount
metadata:
  name: tensorizer-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: tensorizer-role
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tensorizer-rolebinding
subjects:
  - kind: ServiceAccount
    name: tensorizer-sa
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: tensorizer-role
