apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tensorizer-vllm
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  source:
    repoURL: https://github.com/coreweave/tensorizer
    path: helm/tensorizer-vllm
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
