name: build-and-deploy

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2
      - name: Build
        run: docker build -t example/vllm:${{ github.sha }} .
      - name: Scan
        uses: aquasecurity/trivy-action@0.20.0
        with:
          image-ref: example/vllm:${{ github.sha }}
      - name: Login
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Push
        run: docker push example/vllm:${{ github.sha }}
      - name: Helm Upgrade
        run: helm upgrade --install tensorizer helm/tensorizer-vllm --set image=example/vllm:${{ github.sha }} --namespace test --create-namespace
