name: Build

on:
  release:
    types: [published]

jobs:
  build_dist:
    name: Build distribution on Ubuntu
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v3
        with:
          python-version: '3.10'

      - name: Install build dependencies
        run: python -m pip install --no-cache-dir -U setuptools build

      - name: Build distribution
        run: python -m build

      - uses: actions/upload-artifact@v3
        with:
          path: ./dist/*

  upload_dist:
    needs: [ build_dist ]
    name: Upload distribution to PyPI
    runs-on: ubuntu-22.04
    if: github.event_name == 'release' && github.event.action == 'published'
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: artifact
          path: dist

      - uses: pypa/gh-action-pypi-publish@release/v1.8.1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}