name: Test

on: [push, pull_request]

jobs:
  run_tests:
    name: Run tests
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install dependencies
        run: >
          python -m pip install -e . &&
          python -m pip install -r tests/requirements.txt

      - name: Install Redis
        run: sudo apt-get install -y redis-server

      - name: Install libsodium
        run: sudo apt-get install -y libsodium23

      - name: Run tests
        run: python -m unittest discover tests/ --verbose
